package org.tdp2.ph4;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/valuesMPU") 
public class MainController {
  @Autowired // This means to get the bean called valuesMPURepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private ValuesMPURepository valuesMPURepository;

  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String addNewValuesMPU (@RequestBody ValuesMPU valuesMPU) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request
  

    valuesMPURepository.save(valuesMPU);
    return "Saved";
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<ValuesMPU> getAllValuesMPU() {
    // This returns a JSON or XML with the valuesMPU
    return valuesMPURepository.findAll();
  }
}